DROP DATABASE IF EXISTS photobooth;
CREATE DATABASE photobooth;

USE photobooth;

CREATE TABLE Photo (
  id        INTEGER PRIMARY KEY AUTO_INCREMENT,
  email     INTEGER,
  photoPath VARCHAR(512) UNIQUE,
  thumbNail VARCHAR(512) UNIQUE,
  whenTaken TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT='When the picture was taken'
);

CREATE TABLE Person (
  id  INTEGER PRIMARY KEY AUTO_INCREMENT,
  pname VARCHAR(45) UNIQUE,
  email VARCHAR(255)
);

